### ISSUE TITLE
please update the debian packaging

### ISSUE THREAD

**Issue by LocutusOfBorg** [suntong/shc-build#2]
Hi, can you please update the Debian packaging?

the ddpo page is still showing the old page
thanks!

**Comment by suntong** [comment]
Hmm? `shc/3.8.9b-1` has been uploaded to Debian on Sep 26. what else are you asking?

Ref:

From: Debian Bug Tracking System owner@bugs.debian.org
Date: Sat, Sep 26, 2015 at 12:39 PM
Subject: Bug#799529 closed by Gianfranco Costamagna @yahoo.it (Re: Bug#799529: RFS: shc/3.8.9b-1 new upstream release)
To: Tong Sun @gmail.com

This is an automatic notification regarding your Bug report
which was filed against the sponsorship-requests package:

#799529: RFS: shc/3.8.9b-1 new upstream release

It has been closed by Gianfranco Costamagna @yahoo.it

**Comment by LocutusOfBorg** [comment]
true, the ddpo is erroring I guess because the tag is not pushed
Git
ERROR
https://qa.debian.org/developer.php?email=suntong001%40users.sourceforge.net

well, nevermind then

**Comment by suntong** [comment]
Ops, I changed my github id recently, and the https://github.com/suntong001/shc-build is now redirecting to https://github.com/suntong/shc-build. But,...

how can I handle the case that my https://github.com/suntong/shc-build contains only the build, not source code? I'm guessing srv/scratch/qa.debian.org is expecting a full Debianized source tree, right?

**Comment by LocutusOfBorg** [comment]
yes, otherwise please use the -b flag in VCS- fields, to tell it the branch

e.g.

```
Vcs-Git: git://anonscm.debian.org/freewx/wx.git -b wx3.0-debian
Vcs-Browser: https://anonscm.debian.org/gitweb/?p=freewx/wx.git;a=shortlog;h=refs/heads/wx3.0-debian
```
